### PR TITLE
adding functionality to allow for multiple service calls. This preven…

### PR DESCRIPTION
**Pull request by vchu**
…ts the listener from wiping the last speech command

### CODE REVIEW

**Comment by vchu** [comment]
@yuchen93 @jainajinkya 

Hi folks, Andrea mentioned that there seem to be an issue with multiple speech calls being a possible thing that breaks hello world. 

This might not be related at all, but just FYI - I've added in a parameter in the config file that allows several service calls to the same listener. Basically, if the flag is set to true, then the listener doesn't check if the command has been provided before. It literally just returns the last speech command it heard.

**Comment by vchu** [comment]
Also FYI - I was able to run the hello world demo in simulation without any errors. I am on the poli_config branch of vector_v1. Maybe something to do with that as opposed to speech?

**Comment by yuchen93** [comment]
We tried the hello world code Asif gave us and it is different from the one we had. That worked so we compared the code and found it was because the speech node being initialized twice in our version.

Yuchen

**Comment by vchu** [comment]
Got it. We really need to at some point have a central committed version of working. The one in si-machines works, but passing around versions via zip file shouldn't be done in the long run...

@mrana6 @jainajinkya Just FYI - unless someone puts the latest cleaned up version somewhere, I'm not going to be able to help if anything ever breaks. I normally when committing something that will break hello world, go back and check with the version we have in si-machines, but that won't work since everyone doesn't have access to that repo.

**Comment by mrana6** [comment]
@vchu I have the latest version under gt-rail-internal/HLP-R/hlpr_hello_world for the time being. I am 80% done with cleaning up and commenting the code. This is the same version @yuchen93 and @jainajinkya are using and they have access to it as well.

**Comment by vchu** [comment]
@mrana6 Great - good to know. I'll make sure any changes then I commit work with that version. Do @yuchen93 and @jainajinkya have access to that repo? If anything needs to be changed API wise, I'll directly change it in that repo in the future (until it gets promoted)

**Comment by mrana6** [comment]
Yes they do have access as far as I know

**Pull request merged**
